//mock data for creating an issue
var createIssue = { action: 'created',
  issue: 
   { url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/1',
     repository_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/1/labels{/name}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/1/comments',
     events_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/1/events',
     html_url: 'https://github.com/javan-rajpopat/HelloYou/issues/1',
     id: 509506043,
     node_id: 'MDU6SXNzdWU1MDk1MDYwNDM=',
     number: 1,
     title: 'sdf',
     user: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     labels: [],
     state: 'open',
     locked: false,
     assignee: null,
     assignees: [],
     milestone: null,
     comments: 0,
     created_at: '2019-10-19T20:30:14Z',
     updated_at: '2019-10-19T20:48:28Z',
     closed_at: null,
     author_association: 'OWNER',
     body: 'sdf' },
  comment: 
   { url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/comments/544196167',
     html_url: 'https://github.com/javan-rajpopat/HelloYou/issues/1#issuecomment-544196167',
     issue_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/1',
     id: 544196167,
     node_id: 'MDEyOklzc3VlQ29tbWVudDU0NDE5NjE2Nw==',
     user: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     created_at: '2019-10-19T20:48:28Z',
     updated_at: '2019-10-19T20:48:28Z',
     author_association: 'OWNER',
     body: 'sdfdf' },
  repository: 
   { id: 205071855,
     node_id: 'MDEwOlJlcG9zaXRvcnkyMDUwNzE4NTU=',
     name: 'HelloYou',
     full_name: 'javan-rajpopat/HelloYou',
     private: false,
     owner: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     html_url: 'https://github.com/javan-rajpopat/HelloYou',
     description: 'A complete chat application built using node.js and socket.io, with features like photo sharing, emojis and GIFs',
     fork: false,
     url: 'https://api.github.com/repos/javan-rajpopat/HelloYou',
     forks_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/forks',
     keys_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/teams',
     hooks_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/hooks',
     issue_events_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/events{/number}',
     events_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/events',
     assignees_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/assignees{/user}',
     branches_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/branches{/branch}',
     tags_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/tags',
     blobs_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/languages',
     stargazers_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/stargazers',
     contributors_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/contributors',
     subscribers_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/subscribers',
     subscription_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/subscription',
     commits_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/contents/{+path}',
     compare_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/merges',
     archive_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/downloads',
     issues_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/issues{/number}',
     pulls_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/labels{/name}',
     releases_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/releases{/id}',
     deployments_url: 'https://api.github.com/repos/javan-rajpopat/HelloYou/deployments',
     created_at: '2019-08-29T03:22:00Z',
     updated_at: '2019-08-29T03:26:34Z',
     pushed_at: '2019-08-29T03:26:33Z',
     git_url: 'git://github.com/javan-rajpopat/HelloYou.git',
     ssh_url: 'git@github.com:javan-rajpopat/HelloYou.git',
     clone_url: 'https://github.com/javan-rajpopat/HelloYou.git',
     svn_url: 'https://github.com/javan-rajpopat/HelloYou',
     homepage: null,
     size: 627,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'JavaScript',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     archived: false,
     disabled: false,
     open_issues_count: 1,
     license: null,
     forks: 0,
     open_issues: 1,
     watchers: 0,
     default_branch: 'master' },
  sender: 
   { login: 'javan-rajpopat',
     id: 43393611,
     node_id: 'MDQ6VXNlcjQzMzkzNjEx',
     avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/javan-rajpopat',
     html_url: 'https://github.com/javan-rajpopat',
     followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
     following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
     gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
     organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
     repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
     events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
     received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
     type: 'User',
     site_admin: false },
  installation: 
   { id: 3311507,
     node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzMxMTUwNw==' } }

//mock data on deleting an issue
var deleteIssue = { action: 'deleted',
  issue: 
   { url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/32',
     repository_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/32/labels{/name}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/32/comments',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/32/events',
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode/issues/32',
     id: 509505957,
     node_id: 'MDU6SXNzdWU1MDk1MDU5NTc=',
     number: 32,
     title: 'sdf',
     user: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     labels: [],
     state: 'open',
     locked: false,
     assignee: null,
     assignees: [],
     milestone: null,
     comments: 0,
     created_at: '2019-10-19T20:29:31Z',
     updated_at: '2019-10-19T20:29:31Z',
     closed_at: null,
     author_association: 'OWNER',
     body: 'sdf' },
  repository: 
   { id: 163788461,
     node_id: 'MDEwOlJlcG9zaXRvcnkxNjM3ODg0NjE=',
     name: '50DaysOfCode',
     full_name: 'javan-rajpopat/50DaysOfCode',
     private: false,
     owner: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     description: '50 days coding challenge started on 1st January 2019',
     fork: false,
     url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     forks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/forks',
     keys_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/teams',
     hooks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/hooks',
     issue_events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/events{/number}',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/events',
     assignees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/assignees{/user}',
     branches_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/branches{/branch}',
     tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/tags',
     blobs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/languages',
     stargazers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/stargazers',
     contributors_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contributors',
     subscribers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscribers',
     subscription_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscription',
     commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contents/{+path}',
     compare_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/merges',
     archive_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/downloads',
     issues_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues{/number}',
     pulls_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/labels{/name}',
     releases_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/releases{/id}',
     deployments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/deployments',
     created_at: '2019-01-02T03:11:27Z',
     updated_at: '2019-03-04T03:31:33Z',
     pushed_at: '2019-02-23T04:17:45Z',
     git_url: 'git://github.com/javan-rajpopat/50DaysOfCode.git',
     ssh_url: 'git@github.com:javan-rajpopat/50DaysOfCode.git',
     clone_url: 'https://github.com/javan-rajpopat/50DaysOfCode.git',
     svn_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     homepage: null,
     size: 4007,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'Java',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     archived: false,
     disabled: false,
     open_issues_count: 21,
     license: null,
     forks: 0,
     open_issues: 21,
     watchers: 0,
     default_branch: 'master' },
  sender: 
   { login: 'javan-rajpopat',
     id: 43393611,
     node_id: 'MDQ6VXNlcjQzMzkzNjEx',
     avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/javan-rajpopat',
     html_url: 'https://github.com/javan-rajpopat',
     followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
     following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
     gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
     organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
     repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
     events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
     received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
     type: 'User',
     site_admin: false },
  installation: 
   { id: 3311507,
     node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzMxMTUwNw==' } }

//mock data on commenting on an issue
var commentIssue = { action: 'created',
  issue: 
   { url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31',
     repository_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31/labels{/name}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31/comments',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31/events',
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode/issues/31',
     id: 509505561,
     node_id: 'MDU6SXNzdWU1MDk1MDU1NjE=',
     number: 31,
     title: 'sda',
     user: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     labels: [],
     state: 'open',
     locked: false,
     assignee: null,
     assignees: [],
     milestone: null,
     comments: 0,
     created_at: '2019-10-19T20:25:39Z',
     updated_at: '2019-10-19T20:50:32Z',
     closed_at: null,
     author_association: 'OWNER',
     body: 'ads' },
  comment: 
   { url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/comments/544196286',
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode/issues/31#issuecomment-544196286',
     issue_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31',
     id: 544196286,
     node_id: 'MDEyOklzc3VlQ29tbWVudDU0NDE5NjI4Ng==',
     user: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     created_at: '2019-10-19T20:50:32Z',
     updated_at: '2019-10-19T20:50:32Z',
     author_association: 'OWNER',
     body: 'sdf' },
  repository: 
   { id: 163788461,
     node_id: 'MDEwOlJlcG9zaXRvcnkxNjM3ODg0NjE=',
     name: '50DaysOfCode',
     full_name: 'javan-rajpopat/50DaysOfCode',
     private: false,
     owner: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     description: '50 days coding challenge started on 1st January 2019',
     fork: false,
     url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     forks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/forks',
     keys_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/teams',
     hooks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/hooks',
     issue_events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/events{/number}',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/events',
     assignees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/assignees{/user}',
     branches_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/branches{/branch}',
     tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/tags',
     blobs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/languages',
     stargazers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/stargazers',
     contributors_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contributors',
     subscribers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscribers',
     subscription_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscription',
     commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contents/{+path}',
     compare_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/merges',
     archive_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/downloads',
     issues_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues{/number}',
     pulls_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/labels{/name}',
     releases_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/releases{/id}',
     deployments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/deployments',
     created_at: '2019-01-02T03:11:27Z',
     updated_at: '2019-03-04T03:31:33Z',
     pushed_at: '2019-02-23T04:17:45Z',
     git_url: 'git://github.com/javan-rajpopat/50DaysOfCode.git',
     ssh_url: 'git@github.com:javan-rajpopat/50DaysOfCode.git',
     clone_url: 'https://github.com/javan-rajpopat/50DaysOfCode.git',
     svn_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     homepage: null,
     size: 4007,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'Java',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     archived: false,
     disabled: false,
     open_issues_count: 20,
     license: null,
     forks: 0,
     open_issues: 20,
     watchers: 0,
     default_branch: 'master' },
  sender: 
   { login: 'javan-rajpopat',
     id: 43393611,
     node_id: 'MDQ6VXNlcjQzMzkzNjEx',
     avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/javan-rajpopat',
     html_url: 'https://github.com/javan-rajpopat',
     followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
     following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
     gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
     organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
     repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
     events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
     received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
     type: 'User',
     site_admin: false },
  installation: 
   { id: 3311507,
     node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzMxMTUwNw==' } }

//mock data on closing an issue
var closeIssue = { action: 'closed',
  issue: 
   { url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31',
     repository_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31/labels{/name}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31/comments',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/31/events',
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode/issues/31',
     id: 509505561,
     node_id: 'MDU6SXNzdWU1MDk1MDU1NjE=',
     number: 31,
     title: 'sda',
     user: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     labels: [],
     state: 'closed',
     locked: false,
     assignee: null,
     assignees: [],
     milestone: null,
     comments: 1,
     created_at: '2019-10-19T20:25:39Z',
     updated_at: '2019-10-19T20:51:02Z',
     closed_at: '2019-10-19T20:51:02Z',
     author_association: 'OWNER',
     body: 'ads' },
  repository: 
   { id: 163788461,
     node_id: 'MDEwOlJlcG9zaXRvcnkxNjM3ODg0NjE=',
     name: '50DaysOfCode',
     full_name: 'javan-rajpopat/50DaysOfCode',
     private: false,
     owner: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     description: '50 days coding challenge started on 1st January 2019',
     fork: false,
     url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     forks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/forks',
     keys_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/teams',
     hooks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/hooks',
     issue_events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/events{/number}',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/events',
     assignees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/assignees{/user}',
     branches_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/branches{/branch}',
     tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/tags',
     blobs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/languages',
     stargazers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/stargazers',
     contributors_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contributors',
     subscribers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscribers',
     subscription_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscription',
     commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contents/{+path}',
     compare_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/merges',
     archive_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/downloads',
     issues_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues{/number}',
     pulls_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/labels{/name}',
     releases_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/releases{/id}',
     deployments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/deployments',
     created_at: '2019-01-02T03:11:27Z',
     updated_at: '2019-03-04T03:31:33Z',
     pushed_at: '2019-02-23T04:17:45Z',
     git_url: 'git://github.com/javan-rajpopat/50DaysOfCode.git',
     ssh_url: 'git@github.com:javan-rajpopat/50DaysOfCode.git',
     clone_url: 'https://github.com/javan-rajpopat/50DaysOfCode.git',
     svn_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     homepage: null,
     size: 4007,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'Java',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     archived: false,
     disabled: false,
     open_issues_count: 19,
     license: null,
     forks: 0,
     open_issues: 19,
     watchers: 0,
     default_branch: 'master' },
  sender: 
   { login: 'javan-rajpopat',
     id: 43393611,
     node_id: 'MDQ6VXNlcjQzMzkzNjEx',
     avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/javan-rajpopat',
     html_url: 'https://github.com/javan-rajpopat',
     followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
     following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
     gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
     organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
     repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
     events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
     received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
     type: 'User',
     site_admin: false },
  installation: 
   { id: 3311507,
     node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzMxMTUwNw==' } }

//mock data on pushing a commit
var pushCommit = { ref: 'refs/heads/master',
  before: '2a993365dc09cca1417b7f30bfc9eba77366f9aa',
  after: '22359005ec5e0791e28294576fc6c40c61e4cbdb',
  repository: 
   { id: 163788461,
     node_id: 'MDEwOlJlcG9zaXRvcnkxNjM3ODg0NjE=',
     name: '50DaysOfCode',
     full_name: 'javan-rajpopat/50DaysOfCode',
     private: false,
     owner: 
      { name: 'javan-rajpopat',
        email: '43393611+javan-rajpopat@users.noreply.github.com',
        login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     description: '50 days coding challenge started on 1st January 2019',
     fork: false,
     url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     forks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/forks',
     keys_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/teams',
     hooks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/hooks',
     issue_events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/events{/number}',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/events',
     assignees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/assignees{/user}',
     branches_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/branches{/branch}',
     tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/tags',
     blobs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/languages',
     stargazers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/stargazers',
     contributors_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contributors',
     subscribers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscribers',
     subscription_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscription',
     commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contents/{+path}',
     compare_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/merges',
     archive_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/downloads',
     issues_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues{/number}',
     pulls_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/labels{/name}',
     releases_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/releases{/id}',
     deployments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/deployments',
     created_at: 1546398687,
     updated_at: '2019-03-04T03:31:33Z',
     pushed_at: 1571518335,
     git_url: 'git://github.com/javan-rajpopat/50DaysOfCode.git',
     ssh_url: 'git@github.com:javan-rajpopat/50DaysOfCode.git',
     clone_url: 'https://github.com/javan-rajpopat/50DaysOfCode.git',
     svn_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     homepage: null,
     size: 4007,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'Java',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     archived: false,
     disabled: false,
     open_issues_count: 19,
     license: null,
     forks: 0,
     open_issues: 19,
     watchers: 0,
     default_branch: 'master',
     stargazers: 0,
     master_branch: 'master' },
  pusher: 
   { name: 'javan-rajpopat',
     email: '43393611+javan-rajpopat@users.noreply.github.com' },
  sender: 
   { login: 'javan-rajpopat',
     id: 43393611,
     node_id: 'MDQ6VXNlcjQzMzkzNjEx',
     avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/javan-rajpopat',
     html_url: 'https://github.com/javan-rajpopat',
     followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
     following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
     gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
     organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
     repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
     events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
     received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
     type: 'User',
     site_admin: false },
  installation: 
   { id: 3311507,
     node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzMxMTUwNw==' },
  created: false,
  deleted: false,
  forced: false,
  base_ref: null,
  compare: 'https://github.com/javan-rajpopat/50DaysOfCode/compare/2a993365dc09...22359005ec5e',
  commits: 
   [ { id: '22359005ec5e0791e28294576fc6c40c61e4cbdb',
       tree_id: '4825c38561047e322611daa84e2114052ec13bca',
       distinct: true,
       message: 'package recieved\n\npackage',
       timestamp: '2019-10-19T16:52:15-04:00',
       url: 'https://github.com/javan-rajpopat/50DaysOfCode/commit/22359005ec5e0791e28294576fc6c40c61e4cbdb',
       author: [Object],
       committer: [Object],
       added: [],
       removed: [],
       modified: [Array] } ],
  head_commit: 
   { id: '22359005ec5e0791e28294576fc6c40c61e4cbdb',
     tree_id: '4825c38561047e322611daa84e2114052ec13bca',
     distinct: true,
     message: 'package recieved\n\npackage',
     timestamp: '2019-10-19T16:52:15-04:00',
     url: 'https://github.com/javan-rajpopat/50DaysOfCode/commit/22359005ec5e0791e28294576fc6c40c61e4cbdb',
     author: 
      { name: 'Javan Rajpopat',
        email: '43393611+javan-rajpopat@users.noreply.github.com',
        username: 'javan-rajpopat' },
     committer: 
      { name: 'GitHub',
        email: 'noreply@github.com',
        username: 'web-flow' },
     added: [],
     removed: [],
     modified: [ 'README.md' ] } }

//mock data on creating a wiki page
var createWikiPage = { pages: 
   [ { page_name: 'Home',
       title: 'Home',
       summary: null,
       action: 'created',
       sha: '870f089958b92a5df23868046dc1494bca49e8d3',
       html_url: 'https://github.com/javan-rajpopat/50DaysOfCode/wiki/Home' } ],
  repository: 
   { id: 163788461,
     node_id: 'MDEwOlJlcG9zaXRvcnkxNjM3ODg0NjE=',
     name: '50DaysOfCode',
     full_name: 'javan-rajpopat/50DaysOfCode',
     private: false,
     owner: 
      { login: 'javan-rajpopat',
        id: 43393611,
        node_id: 'MDQ6VXNlcjQzMzkzNjEx',
        avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/javan-rajpopat',
        html_url: 'https://github.com/javan-rajpopat',
        followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
        following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
        gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
        organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
        repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
        events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
        type: 'User',
        site_admin: false },
     html_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     description: '50 days coding challenge started on 1st January 2019',
     fork: false,
     url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode',
     forks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/forks',
     keys_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/teams',
     hooks_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/hooks',
     issue_events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/events{/number}',
     events_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/events',
     assignees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/assignees{/user}',
     branches_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/branches{/branch}',
     tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/tags',
     blobs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/languages',
     stargazers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/stargazers',
     contributors_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contributors',
     subscribers_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscribers',
     subscription_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/subscription',
     commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/contents/{+path}',
     compare_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/merges',
     archive_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/downloads',
     issues_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/issues{/number}',
     pulls_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/labels{/name}',
     releases_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/releases{/id}',
     deployments_url: 'https://api.github.com/repos/javan-rajpopat/50DaysOfCode/deployments',
     created_at: '2019-01-02T03:11:27Z',
     updated_at: '2019-10-19T20:52:17Z',
     pushed_at: '2019-10-19T20:52:15Z',
     git_url: 'git://github.com/javan-rajpopat/50DaysOfCode.git',
     ssh_url: 'git@github.com:javan-rajpopat/50DaysOfCode.git',
     clone_url: 'https://github.com/javan-rajpopat/50DaysOfCode.git',
     svn_url: 'https://github.com/javan-rajpopat/50DaysOfCode',
     homepage: null,
     size: 4007,
     stargazers_count: 0,
     watchers_count: 0,
     language: 'Java',
     has_issues: true,
     has_projects: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     archived: false,
     disabled: false,
     open_issues_count: 19,
     license: null,
     forks: 0,
     open_issues: 19,
     watchers: 0,
     default_branch: 'master' },
  sender: 
   { login: 'javan-rajpopat',
     id: 43393611,
     node_id: 'MDQ6VXNlcjQzMzkzNjEx',
     avatar_url: 'https://avatars2.githubusercontent.com/u/43393611?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/javan-rajpopat',
     html_url: 'https://github.com/javan-rajpopat',
     followers_url: 'https://api.github.com/users/javan-rajpopat/followers',
     following_url: 'https://api.github.com/users/javan-rajpopat/following{/other_user}',
     gists_url: 'https://api.github.com/users/javan-rajpopat/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/javan-rajpopat/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/javan-rajpopat/subscriptions',
     organizations_url: 'https://api.github.com/users/javan-rajpopat/orgs',
     repos_url: 'https://api.github.com/users/javan-rajpopat/repos',
     events_url: 'https://api.github.com/users/javan-rajpopat/events{/privacy}',
     received_events_url: 'https://api.github.com/users/javan-rajpopat/received_events',
     type: 'User',
     site_admin: false },
  installation: 
   { id: 3311507,
     node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzMxMTUwNw==' } }

module.exports = {
  createIssue,
  deleteIssue,
  commentIssue,
  closeIssue,
  pushCommit,
  createWikiPage
};